name: dart_rtc_client
version: 0.1.0
author: Sami Ylonen <sami.ylonen@gmail.com>
description: A Dart WebRTC Client library
dependencies:
  unittest: 0.4.4+4
  dart_rtc_common:
    git: git://github.com/samiy-xx/dart_rtc_common.git
