name: dart_rtc_client
version: 0.2.0
author: Sami Ylonen <sami.ylonen@gmail.com>
description: A Dart WebRTC Client library
dependencies:
  browser: any
  dart_rtc_common:
    git: git://github.com/samiy-xx/dart_rtc_common.git
  logging_handlers: 0.5.0+2
  unittest: 0.5.5
